# fly.toml app configuration file generated for sacred-berkeley on 2024-12-28T14:03:47-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sacred-berkeley'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
